// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVdQs1NB-LytxK5bnoy5OMQzcofNZyd_0',
    appId: '1:72910334063:android:a50f8c27cafe77769bc59a',
    messagingSenderId: '72910334063',
    projectId: 'rentalapp-df651',
    storageBucket: 'rentalapp-df651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntz8_6UjAMrU2Wo8O3yfoP43zf-uzSVo',
    appId: '1:72910334063:ios:c1a9291c7770d6269bc59a',
    messagingSenderId: '72910334063',
    projectId: 'rentalapp-df651',
    storageBucket: 'rentalapp-df651.appspot.com',
    androidClientId: '72910334063-7bgr3eghue3v7bb6rss538g7hu12m784.apps.googleusercontent.com',
    iosClientId: '72910334063-enalnij7iiuhu4114fgqjmpvu177qeeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.rental',
  );
}
